const CONFIG = {
    titleWeb: "Gửi Ngân",
    introTitle: 'Ngân <3',
    introDesc: `t lỡ thích m rồi...`,
    btnIntro: '^^HiHi^^',
    title: 'Làm ny t nhé?',
    desc: ':>',
    btnYes: 'oke :333',
    btnNo: 'Không nha :>',
    question: ':D',
    btnReply: 'Gửi cho bạn <3',
    reply: 'Yêu thì yêu mà không yêu thì yêu <33333333',
    mess: '😘',
    messDesc: 'thế thì ib mes t đi <3',
    btnAccept: 'Okiiiii lun <3',
    messLink: https://www.facebook.com/messages/t/100034533873258
